### ISSUE TITLE
No API KEY found

### ISSUE THREAD

**Issue by vasmarfas** [MoeZilla/stable-diffusion-telegram-bot#7]
Traceback (most recent call last):
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/stable-diffusion-telegram-bot/main.py", line 88, in <module>
    app.run()
  File "/var/www/miniconda3/lib/python3.10/site-packages/pyrogram/methods/utilities/run.py", line 58, in run
    self.start()
  File "/var/www/miniconda3/lib/python3.10/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/var/www/miniconda3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/var/www/miniconda3/lib/python3.10/site-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/var/www/miniconda3/lib/python3.10/site-packages/pyrogram/methods/auth/connect.py", line 38, in connect
    self.load_config()
  File "/var/www/miniconda3/lib/python3.10/site-packages/pyrogram/client.py", line 616, in load_config
    raise AttributeError("No API Key found. More info: https://docs.pyrogram.org/intro/setup")
AttributeError: No API Key found. More info: https://docs.pyrogram.org/intro/setup

What i have to do to make bot working?

**Comment by vasmarfas** [comment]
![image](https://user-images.githubusercontent.com/37144504/235437016-3c07a3ba-8f57-44bb-9630-43377f869220.png)

**Comment by vasmarfas** [comment]
![image](https://user-images.githubusercontent.com/37144504/235438193-d9afd2a3-7c55-47da-8be5-ce90e5264621.png)
I just harcoded this in main.py and bot is working. It generates an image (i can see it by GPU load %), but don't send generated picture. Traceback:
name 'url' is not defined
Traceback (most recent call last):
  File "/var/www/miniconda3/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 224, in handler_worker
    await self.loop.run_in_executor(
  File "/var/www/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/media/bad-hdd-nextcloud/nextcloud-data/Programms/stable-diffusion-telegram-bot/main.py", line 59, in draw
    response2 = requests.post(url=f'{url}/sdapi/v1/png-info',
NameError: name 'url' is not defined
